### ISSUE TITLE
Default missing values in agpypeline.environment when running pipeline

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#60]
**Task to do**
Permit the pipeline to run when certain currently mandated data is not available

**Reason**
It should be possible to run the pipeline without needing Experiment data (such as crop name, timestamp, e tc)

**Result**
Allowing the user to not specify certain data allows the a greater variety of situations

**Details**
Report as warnings and use default values when Experiment data is not available. The list of values to allow defaults are:
- Study name
- Season
- ~Germplasm name~
- ~Collecting site~
These last 2 values are not part of this ticket and are moved to a new ticket

**Comment by jvanderleeuw** [comment]
Difficulties when trying to install dependencies that are keeping the agpypeline library from being imported. When I check on my local file system I see that agpypeline is installed, and it looks as if it installs when I do the GitHub workflow on transformer_opendronemap, but then it is not correctly installed. I tried different installations and created other pypi libraries using agpypeline's code at a point to test the problem, but without success.

When I build an image through the dockerfile, it says that it cannot find a version of agpypeline that satisfies the requirement beyond agpypeline==0.0.10. This is an issue because after 0.0.10 the structure of the agpypeline library was changed. I tried uninstalling and reinstalling versions of agpypeline to test, but with the same result. 

Earlier there was an problem regarding that transformer-opendronemap was operating through python3.5 rather than through python3.7, but that seems to have been fixed. When I run python3 --version through the GitHub workflow after doing the python3.7 installation, it appears that the system is using python3.7, as is wanted

**Comment by Chris-Schnaufer** [comment]
Looking at the output from the GitHub action, it shows that the gdal version is incorrect and needs to be 2.4.4.
```__main__.GDALConfigError: Version mismatch 2.2.3 != 2.4.4```
Updating the YAML file to install version 2.4.4.* should fix the issue

**Comment by Chris-Schnaufer** [comment]
Closing as completed. The conflict was resolved
