### ISSUE TITLE
Agpypeline library updated to support Python 3.5+

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#72]
**The current behavior or issue**
The agpypeline library is supposed to support Python3.5 but has code that's not available for that version causing the library to crasgh

**The steps taken to reproduce the behavior or issue, or specify a location where the steps were recorded**
Run Python3.5 pylint over environment.py and `fromisoformat()` call is in error: https://github.com/AgPipeline/agpypeline/blob/34b39c631f019bcb77a1f929374ecbcc4ea3578d/agpypeline/environment.py#L97

**Expected behavior**
Python 3.5 and later is supported

**Screenshots**

**Add other supporting information that may be useful**
Python 3.5

**Completion criteria**
This is done when:
- [ ] the library python files pass Python 3.5 pylint check

**Comment by jvanderleeuw** [comment]
Ticket no longer valid. Instead transformer-opendronemap is being built with python3.7 (instead of its previous python3.5)

[Branch used before closing](https://github.com/AgPipeline/agpypeline/tree/testing)

[New Branch opened for transformer_opendronemap](https://github.com/AgPipeline/transformer-opendronemap/tree/using_python3.7)
